services:
  # -----------------------------------------------------------------
  # POSTGRESQL (Cold Storage - Settings and History LOGS)
  # -----------------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # -----------------------------------------------------------------
  # REDIS (Hot Storage - Counters and Rate Limiting)
  # -----------------------------------------------------------------
  redis:
    image: redis:alpine
    container_name: redis-db
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - main-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # -----------------------------------------------------------------
  # REDPANDA (Event Streaming - Kafka Compatible)
  # -----------------------------------------------------------------
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-streaming
    command:
      - redpanda start
      - --smp 1 # Dev config
      - --memory 1G # RAM Limiter
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:8084
    ports:
      - "${REDPANDA_PORT}:9092"
      - "9644:9644" # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - main-net

  # -----------------------------------------------------------------
  # REDPANDA CONSOLE (UI to see topics and messages)
  # -----------------------------------------------------------------
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yaml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yaml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "${REDPANDA_CONSOLE_PORT}:8080"
    networks:
      - main-net
    depends_on:
      - redpanda

volumes:
  postgres_data:
  redis_data:
  redpanda_data:

networks:
  main-net:
    driver: bridge
